def main():
    input_string = input("Enter a string: ")
    rules = {}

    with open("cfg.txt") as file:
        lines = file.read().splitlines()

    for line in lines:
        line = line.replace(' ', '')
        lhs = line[0]
        rhs = line[3:]

        if lhs in rules:
            rules[lhs].append(rhs)
        else:
            rules[lhs] = [rhs]

    length = len(input_string)
    table = [[set() for _ in range(length)] for _ in range(length)]

    for i in range(length):
        for variable in rules:
            if input_string[i] in rules[variable]:
                table[i][i].add(variable)

    for h in range(1, length):
        for i in range(length - h):
            j = i + h

            for k in range(h):
                result = cross_product(table[i][i + k], table[i + k + 1][j])

                for item in result:
                    for variable in rules:
                        if item in rules[variable]:
                            table[i][j].add(variable)

    if list(rules.keys())[0] in table[0][length - 1]:
        print(f'String "{input_string}" can be generated by the CFG.')
    else:
        print(f'String "{input_string}" can NOT be generated by the CFG.')


def cross_product(set1, set2):
    result = set()

    for variable1 in set1:
        for variable2 in set2:
            result.add(variable1 + variable2)

    return result


if __name__ == "__main__":
    main()
